sudo: required
services:
  - docker
  
before_install:
  - docker build -t afifrafpi/docker-react -f Dockerfile.dev .

script:
  - docker run afifrafpi/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-745276598216"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $$AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"